/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0dc5ecbef00f15aa6d247831764732bf)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	EMAIL_FROM: "Studentmarkedet <noreply@mail.studentmarkedet.org>";
	BETTER_AUTH_SECRET: string;
	LOGIN_CODE_DELIVERY: string;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "BETTER_AUTH_SECRET" | "LOGIN_CODE_DELIVERY" | "RESEND_API_KEY">> {}
}
