/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3e407ff87b12c8f6d99b44df1c770cbe)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
	LOGIN_CODE_DELIVERY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "LOGIN_CODE_DELIVERY">> {}
}
